/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "F:\\vuepress文档库\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-f60a82b6",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f60a82b6").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-a966e9ea",
    path: "/framework/frontFramework/webpack/webpack.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a966e9ea").then(next)
    },
  },
  {
    name: "v-53a6721d",
    path: "/frontEnd/frontBase/css/css3.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-53a6721d").then(next)
    },
  },
  {
    name: "v-1dde2446",
    path: "/frontEnd/frontBase/css/sass.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1dde2446").then(next)
    },
  },
  {
    name: "v-e266e346",
    path: "/frontEnd/frontBase/css/cssBase.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e266e346").then(next)
    },
  },
  {
    name: "v-bd550156",
    path: "/frontEnd/frontBase/html/html.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-bd550156").then(next)
    },
  },
  {
    name: "v-006833b3",
    path: "/frontEnd/frontBase/html/htmlBase.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-006833b3").then(next)
    },
  },
  {
    name: "v-274a78c3",
    path: "/frontEnd/frontBase/javascript/BOM_DOM.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-274a78c3").then(next)
    },
  },
  {
    name: "v-3552fc03",
    path: "/frontEnd/frontBase/javascript/ES6Base.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3552fc03").then(next)
    },
  },
  {
    name: "v-2ee840c3",
    path: "/frontEnd/frontBase/javascript/array.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2ee840c3").then(next)
    },
  },
  {
    name: "v-51863fbb",
    path: "/frontEnd/frontBase/javascript/jsBase.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-51863fbb").then(next)
    },
  },
  {
    name: "v-87c5f4f6",
    path: "/frontEnd/frontBase/javascript/jsModule.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-87c5f4f6").then(next)
    },
  },
  {
    name: "v-b159ae4a",
    path: "/frontEnd/frontBase/javascript/jsDesignMode.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b159ae4a").then(next)
    },
  },
  {
    name: "v-8c429266",
    path: "/frontEnd/frontBase/javascript/string.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-8c429266").then(next)
    },
  },
  {
    name: "v-38d2a07a",
    path: "/frontEnd/frontFrame/nodejs/nodejs.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-38d2a07a").then(next)
    },
  },
  {
    name: "v-2b23797a",
    path: "/frontEnd/frontBase/javascript/jsAdvance.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2b23797a").then(next)
    },
  },
  {
    name: "v-06df272e",
    path: "/frontEnd/frontFrame/react/reactBase.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-06df272e").then(next)
    },
  },
  {
    name: "v-1b0c7413",
    path: "/frontEnd/frontFrame/react/reactAdvance.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1b0c7413").then(next)
    },
  },
  {
    name: "v-4933d92e",
    path: "/frontEnd/frontFrame/react/reactRouter.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4933d92e").then(next)
    },
  },
  {
    name: "v-74f20a6f",
    path: "/frontEnd/frontFrame/vue/vueAdvance.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-74f20a6f").then(next)
    },
  },
  {
    name: "v-4b053269",
    path: "/frontEnd/frontFrame/vue/vueBase.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4b053269").then(next)
    },
  },
  {
    name: "v-1bd89b0b",
    path: "/frontEnd/webTech/browser/browser.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1bd89b0b").then(next)
    },
  },
  {
    name: "v-481beef5",
    path: "/frontEnd/webTech/ajax/ajax.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-481beef5").then(next)
    },
  },
  {
    name: "v-69e085ba",
    path: "/frontEnd/webTech/http/https.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-69e085ba").then(next)
    },
  },
  {
    name: "v-b9fa4d96",
    path: "/frontEnd/webTech/optimize/optimize.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b9fa4d96").then(next)
    },
  },
  {
    name: "v-3db16cf5",
    path: "/frontEnd/webTech/http/http.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3db16cf5").then(next)
    },
  },
  {
    name: "v-b1c67a90",
    path: "/guide/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b1c67a90").then(next)
    },
  },
  {
    path: "/guide/index.html",
    redirect: "/guide/"
  },
  {
    name: "v-1e9cbb4e",
    path: "/normal/algorithm/algorithm.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1e9cbb4e").then(next)
    },
  },
  {
    name: "v-75231cda",
    path: "/normal/algorithm/dataStructure.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-75231cda").then(next)
    },
  },
  {
    name: "v-15b1f7d4",
    path: "/normal/database/mysqlBase.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-15b1f7d4").then(next)
    },
  },
  {
    name: "v-1c46ea20",
    path: "/normal/algorithm/sort.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1c46ea20").then(next)
    },
  },
  {
    name: "v-177da3a3",
    path: "/normal/editTool/idea/idea.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-177da3a3").then(next)
    },
  },
  {
    name: "v-7ea16229",
    path: "/normal/editTool/vim/vim.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7ea16229").then(next)
    },
  },
  {
    name: "v-601afce3",
    path: "/normal/editTool/vscode/vscode.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-601afce3").then(next)
    },
  },
  {
    name: "v-196d1f7c",
    path: "/normal/github/gitNotes.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-196d1f7c").then(next)
    },
  },
  {
    name: "v-159d81a2",
    path: "/normal/nginx/nginx.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-159d81a2").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]